apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: nfs-subdir-external-provisioner
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2021-11-19T16:00:18Z"
  generation: 1
  labels:
    app: nfs-subdir-external-provisioner
    app.kubernetes.io/managed-by: Helm
    chart: nfs-subdir-external-provisioner-4.0.14
    heritage: Helm
    release: nfs-subdir-external-provisioner
  name: nfs-subdir-external-provisioner
  namespace: default
  resourceVersion: "4458273"
  selfLink: /apis/apps/v1/namespaces/default/deployments/nfs-subdir-external-provisioner
  uid: bbb41498-b37e-48fc-9fcb-878e66d790f6
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nfs-subdir-external-provisioner
      release: nfs-subdir-external-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nfs-subdir-external-provisioner
        release: nfs-subdir-external-provisioner
    spec:
      containers:
      - env:
        - name: PROVISIONER_NAME
          value: cluster.local/nfs-subdir-external-provisioner
        - name: NFS_SERVER
          value: 10.242.1.11
        - name: NFS_PATH
          value: /mnt/SSDPool/microk8s-c1
        image: k8s.gcr.io/sig-storage/nfs-subdir-external-provisioner:v4.0.2
        imagePullPolicy: IfNotPresent
        name: nfs-subdir-external-provisioner
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /persistentvolumes
          name: nfs-subdir-external-provisioner-root
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: nfs-subdir-external-provisioner
      serviceAccountName: nfs-subdir-external-provisioner
      terminationGracePeriodSeconds: 30
      volumes:
      - name: nfs-subdir-external-provisioner-root
        nfs:
          path: /mnt/SSDPool/microk8s-c1
          server: 10.242.1.11
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-11-19T16:00:18Z"
    lastUpdateTime: "2021-11-19T16:04:38Z"
    message: ReplicaSet "nfs-subdir-external-provisioner-5d4d4dcbb5" has successfully
      progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-12-09T18:48:25Z"
    lastUpdateTime: "2021-12-09T18:48:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
