apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      app.kubernetes.io/name: helloworld
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: helloworld
        app.kubernetes.io/name: helloworld
    spec:
      containers:
      - image: nginx/nginx:latest
        imagePullPolicy: Always
        name: helloworld
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: static-content
      restartPolicy: Always
      volumes:
      - name: static-content
        persistentVolumeClaim:
          claimName: pvc-helloworld

